[project]
name = "lance-phrase-repro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lancedb>=0.24.0",
    "polars>=1.31.0",
]
